package com.payclip.blaze.pinpad.sdk.ui.activity

import android.app.Activity
import androidx.activity.result.ActivityResult
import com.payclip.blaze.pinpad.sdk.domain.models.login.LoginResult
import com.payclip.blaze.pinpad.sdk.domain.models.payment.PaymentResult

interface ClipResultManager {

    /**
     * Set result when payment process is finished and has a successful response.
     *
     * @param activity The activity that will be finished.
     * @param reference merchant invoice id used in payment process.
     * @param amount amount used in payment process.
     * @param receiptNumber The receipt number associated with the successful payment.
     */
    fun setSuccessResult(
        activity: Activity,
        reference: String,
        amount: String,
        receiptNumber: String,
    )

    /**
     * Set result when login process is finished and has a successful response.
     *
     * @param activity The activity that will be finished.
     * @param code code used in login process.
     * @param successMessage message used in login process.
     */
    fun setLoginSuccessResult(
        activity: Activity,
        code: String,
        successMessage: String
    )

    /**
     * Set result when login process is finished and has a error response.
     *
     * @param activity The activity that will be finished.
     * @param code code used in login process.
     * @param errorMessage message used in login process.
     */
    fun setLoginErrorResult(
        activity: Activity,
        code: String,
        errorMessage: String
    )

    /**
     * Set result when payment process is finished and has a successful response.
     *
     * @param activity The activity that will be finished.
     * @param reference merchant invoice id used in payment process.
     * @param amount amount used in payment process.
     * @param errorCode error code thrown by payment process.
     */
    fun setErrorResult(
        activity: Activity,
        reference: String,
        amount: String,
        errorCode: String
    )

    /**
     * Get result from payment process as string.
     *
     * @param result The result returned by activity contract in ClipLauncher.
     *
     * @return [String] the response.
     */
    fun getResponse(result: ActivityResult): String?

    /**
     * Get error code from error response returned by payment process.
     *
     * @param result The result returned by activity contract in ClipLauncher.
     *
     * @return [String] the error code.
     */
    fun getErrorCode(result: ActivityResult): String?

    /**
     * Get result from login process as string.
     *
     * @param result The result returned by activity contract in ClipLauncher.
     *
     * @return [String] the response from login process.
     */
    fun getLoginResponse(result: ActivityResult): String?

    /**
     * Get result from login process as string.
     *
     * @param result The result returned by activity contract in ClipLauncher.
     *
     * @return [String] the response from login process.
     */
    fun getLoginErrorResponse(result: ActivityResult): String?

    /**
     * Parse response to get payment object with result information.
     *
     * @param result The result returned by activity contract in ClipLauncher.
     * @param response The response generated by `getResponse`.
     * @param onSuccess onSuccess parse listener.
     * @param onFailure onFailure parse listener.
     */
    fun parseResponse(
        result: ActivityResult,
        response: String,
        onSuccess: (result: PaymentResult) -> Unit,
        onFailure: (code: String) -> Unit
    )

    fun parseLoginResponse(
        result: ActivityResult,
        response: String,
        onSuccess: (LoginResult) -> Unit,
        onFailure: (LoginResult) -> Unit
    )
}
