package com.payclip.blaze.pinpad.sdk.ui.activity

import android.app.Activity
import android.content.Intent
import androidx.activity.result.ActivityResult
import com.payclip.blaze.pinpad.sdk.domain.models.payment.PaymentResult

interface ClipResultManager {

    /**
     * Set result when payment process is finished and has a successful response.
     *
     * @param activity The activity that will be finished.
     * @param paymentId payment id used in payment process.
     * @param merchantId merchant invoice id used in payment process.
     * @param amount amount used in payment process.
     */
    fun setSuccessResult(
        activity: Activity,
        paymentId: String,
        merchantId: String,
        amount: String
    )

    /**
     * Set result when payment process is finished and has a successful response.
     *
     * @param activity The activity that will be finished.
     * @param paymentId payment id used in payment process.
     * @param merchantId merchant invoice id used in payment process.
     * @param amount amount used in payment process.
     * @param errorCode error code thrown by payment process.
     */
    fun setErrorResult(
        activity: Activity,
        paymentId: String,
        merchantId: String,
        amount: String,
        errorCode: String
    )

    /**
     * Get result from payment process as string.
     *
     * @param result The result returned by activity contract in ClipLauncher.
     *
     * @return [String] the response.
     */
    fun getResponse(result: ActivityResult): String?

    /**
     * Get error code from error response returned by payment process.
     *
     * @param result The result returned by activity contract in ClipLauncher.
     *
     * @return [String] the error code.
     */
    fun getErrorCode(result: ActivityResult): String?

    /**
     * Parse response to get payment object with result information.
     *
     * @param result The result returned by activity contract in ClipLauncher.
     * @param response The response generated by `getResponse`.
     * @param onSuccess onSuccess parse listener.
     * @param onFailure onFailure parse listener.
     */
    fun parseResponse(
        result: ActivityResult,
        response: String,
        onSuccess: (result: PaymentResult) -> Unit,
        onFailure: (code: String) -> Unit
    )
}
