package com.payclip.blaze.pinpad.sdk.data.providers.serial

import com.payclip.blaze.pinpad.sdk.ClipPaymentSDK
import com.payclip.blaze.pinpad.sdk.domain.providers.serial.SerialNumberProvider

/**
 * Returns the process-stable random serial generated by [ClipPaymentSDK]. The backend only
 * requires the field to be non blank; keeping it stable per process lets the backend correlate
 * requests coming from the same integration session.
 */
internal class RandomSerialNumberProvider : SerialNumberProvider {

    override fun getSerialNumber(): String = ClipPaymentSDK.serialNumber
}
